# Generated by Django 3.2.7 on 2021-11-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NodeId', models.CharField(max_length=50)),
                ('HexAddr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('CurrValue', models.IntegerField()),
                ('TempValue', models.IntegerField()),
                ('NodeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Xbee.node')),
            ],
        ),
    ]
